"""Render the human-facing report and compact PR comment from metrics.

Both renderers are pure functions of the metrics document produced by
:mod:`kicad_bot.metrics`, so they work for any combination of capabilities and
are trivial to unit-test.
"""

from __future__ import annotations

from typing import Any

from .pr_comment import COMMENT_MARKER

REPORT_FILENAME = "report.md"
PR_COMMENT_FILENAME = "pr_comment.md"

_PASS = "✅"
_FAIL = "❌"
_SKIP = "⚪"

_CAPABILITY_TITLES = {
    "verify": "Verify (ERC / DRC)",
    "bom": "BOM availability",
    "diff": "Visual diff",
    "fab": "Fabrication outputs",
}


def _status_icon(passed: bool) -> str:
    return _PASS if passed else _FAIL


def overall_passed(metrics: dict[str, Any]) -> bool:
    """Whether every capability that ran passed its enabled gates."""
    caps = metrics.get("capabilities", {})
    return all(cap.get("passed", True) for cap in caps.values())


def _gate_rows(metrics: dict[str, Any]) -> list[tuple[str, str, str, str]]:
    rows: list[tuple[str, str, str, str]] = []
    for cap_name, cap in metrics.get("capabilities", {}).items():
        for gate_name, gate in cap.get("gates", {}).items():
            if not gate.get("enabled", False):
                status = f"{_SKIP} skipped"
            else:
                status = f"{_PASS} pass" if gate.get("passed", True) else f"{_FAIL} fail"
            rows.append(
                (
                    cap_name,
                    gate_name,
                    str(gate.get("count", 0)),
                    f"{status} — {gate.get('detail', '')}".rstrip(" —"),
                )
            )
    return rows


def _capability_section(cap_name: str, cap: dict[str, Any]) -> list[str]:
    title = _CAPABILITY_TITLES.get(cap_name, cap_name.title())
    lines = [f"### {_status_icon(cap.get('passed', True))} {title}", ""]
    summary = cap.get("summary", {})
    if summary:
        for key, value in summary.items():
            label = key.replace("_", " ").capitalize()
            lines.append(f"- **{label}:** {value}")
        lines.append("")
    return lines


def render_report(metrics: dict[str, Any]) -> str:
    """Render the full ``report.md`` for the run."""
    passed = overall_passed(metrics)
    project = metrics.get("project", {})
    lines: list[str] = [
        "# kicad-bot report",
        "",
        f"**Overall: {_status_icon(passed)} {'PASS' if passed else 'FAIL'}**",
        "",
    ]
    if project:
        name = project.get("name", "(unknown)")
        lines += [f"Project: `{name}`", ""]

    gate_rows = _gate_rows(metrics)
    if gate_rows:
        lines += [
            "## Gates",
            "",
            "| Capability | Gate | Count | Result |",
            "| ---------- | ---- | ----: | ------ |",
        ]
        lines += [f"| {c} | `{g}` | {n} | {r} |" for c, g, n, r in gate_rows]
        lines.append("")

    lines += ["## Details", ""]
    caps = metrics.get("capabilities", {})
    if not caps:
        lines += ["_No capabilities ran._", ""]
    else:
        for cap_name, cap in caps.items():
            lines += _capability_section(cap_name, cap)

    lines += [
        "---",
        "",
        f"_Generated by [kicad-bot](https://github.com/embedded-pro/kicad-bot) v{metrics.get('tool_version', '?')}._",
        "",
    ]
    return "\n".join(lines)


def render_pr_comment(metrics: dict[str, Any]) -> str:
    """Render the compact, idempotent PR comment body."""
    passed = overall_passed(metrics)
    project = metrics.get("project", {})
    name = project.get("name", "")
    header = f"{_status_icon(passed)} **kicad-bot:** {'all checks passed' if passed else 'checks failed'}"
    if name:
        header += f" · `{name}`"

    lines: list[str] = [COMMENT_MARKER, "", header, ""]

    gate_rows = _gate_rows(metrics)
    if gate_rows:
        lines += [
            "| Capability | Gate | Count | Result |",
            "| ---------- | ---- | ----: | ------ |",
        ]
        lines += [f"| {c} | `{g}` | {n} | {r} |" for c, g, n, r in gate_rows]
        lines.append("")

    lines += [
        "<sub>See the full report and artifacts in the workflow run.</sub>",
    ]
    return "\n".join(lines)


def write_reports(metrics: dict[str, Any], output_dir: str) -> tuple[str, str]:
    """Write ``report.md`` and ``pr_comment.md``; return their paths."""
    from pathlib import Path

    out = Path(output_dir)
    out.mkdir(parents=True, exist_ok=True)
    report_path = out / REPORT_FILENAME
    comment_path = out / PR_COMMENT_FILENAME
    report_path.write_text(render_report(metrics), encoding="utf-8")
    comment_path.write_text(render_pr_comment(metrics), encoding="utf-8")
    return str(report_path), str(comment_path)
